### ISSUE TITLE
Task: UI/UX make and import the needed chess pieces

### ISSUE THREAD

**Issue by KodingKevin** [Allen-ISD-Computer-Science/REPO_UltimateChess_2024#11]
Story #8

**Comment by IsaacDaKing** [comment]
Assigned to UI/UX designer @TahmidR2456 and Project Manager @IsaacDaKing 

Check with Product Manager @KodingKevin

**Comment by IsaacDaKing** [comment]
Necessary chess pieces made, but they have not been imported yet as I had difficulty initially working with Unity and Github Projects, but it should be done early by next week

**Comment by TahmidR2456** [comment]
Will try to import pieces over the weekend
