### ISSUE TITLE
Task | Create a way for multiple computers to interact in the same game.

### ISSUE THREAD

**Issue by Neb-Seniah** [Allen-ISD-Computer-Science/REPO_UltimateChess_2024#17]

**Comment by Neb-Seniah** [comment]
Supports Story #3 #7

**Comment by IsaacDaKing** [comment]
Assigned to Engineers @Neb-Seniah and @YeSpectre 

Assistance is likely to be needed

Ask Product Manager @KodingKevin and UI/UX @TahmidR2456 about any visual additions, such as a home screen, that will need to be added in order to facilitate online play.
