### ISSUE TITLE
Task | UI/UX make a ROUGH DRAFT of different minor icons that will be used during the gameplay

### ISSUE THREAD

**Issue by KodingKevin** [Allen-ISD-Computer-Science/REPO_UltimateChess_2024#26]
This includes the icon for the defender shop, attacker shop, and some image ideas representing the powerups that will be used.

story #7

**Comment by TahmidR2456** [comment]
https://docs.google.com/document/d/107JwoT4uSGnWSaq9iUSkeSMnkCtiE1nrHsYIpLQ4-K4/edit

rough outline
