### ISSUE TITLE
Task | UI/UX make the icons that may be used throughout the gameplay

### ISSUE THREAD

**Issue by KodingKevin** [Allen-ISD-Computer-Science/REPO_UltimateChess_2024#31]

**Comment by TahmidR2456** [comment]
Link to currently made icons. Will continue to add more as the project progresses 

https://docs.google.com/presentation/d/16zNyYCcBr7TVR5f3CPy3CroNSZfK8zaqUL69V0j5-8o/edit?usp=sharing
